#!/bin/bash
# install
# This script creates symlinks from the home directory to any desired dotfiles in ~/dotfiles
# Files overwritten will be saved in ~/dotfiles_old

# Variables

dir=~/dotfiles                    # dotfiles directory
backup_dir_name=dotsgotbacked              # old dotfiles backup directory
target_dir=~                      # target directory
target_backup=$target_dir/.$backup_dir_name
files="zlogin vimrc vim zshrc gitconfig gitignore_global aliases osx profile"    # list of files/folders to symlink in homedir
if [-x $0]; then;
    files=$0
endif

echo "Installing skdamico's dotfiles"
echo "($files)\n\n"

# create dotfiles_old in target dir
echo "Creating $target_backup for backup of any existing dotfiles in $target_dir"
mkdir -p $target_backup
echo "...done\n"

# move any existing dotfiles in homedir to backup directory, then create symlinks
for file in $files; do
    echo "Backing up $target_dir/.$file to $target_backup/.$file..."
    mv $target_dir/.$file $target_backup
    echo "Creating symlink $target_dir/.$file to $dir/$file..."
    ln -s $dir/$file $target_dir/.$file
done
echo "...done\n"

echo "Cloning vim plugins..."
cd $dir/vim/bundle
git submodule sync
git submodule update --init
echo "...done\n"

echo "Updating antigen..."
cd $dir/antigen
git pull

cd $target_dir
echo "...done\n"

exec zsh
